### ISSUE TITLE
Hub is not listed as a dependency

### ISSUE THREAD

**Issue by chico1198** [patrickmckenna/bash-utilities#8]
Per our conversation, you mentioned that a CLI add-on named "hub" is necessary to run these scripts.

**Comment by chico1198** [comment]
Even after installing hub, the 'get-url' command still fails.

**Comment by patrickmckenna** [comment]
@chico1198 sorry for the confusion, but [hub](https://hub.github.com) is not actually required. `git remote get-url` is a [regular git command](https://git-scm.com/docs/git-remote). What version of Git are you running? A cursory glance at the different versions of the docs makes me think that it was introduced in `2.7`...
